# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OrzSysDebugDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for OrzSysDebugDemo
  pod 'OrzSysDebug', :path => '../OrzSysDebug.podspec'

end
